
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://170.187.142.135/loki/api/v1/push

scrape_configs:

# local machine logs

- job_name: local
  static_configs:
  - targets:
      - localhost
    labels:
      job: linode
      path: /var/log/*log

version: "3.9"
services:
  promtail:
    image: grafana/promtail:2.0.0
    volumes:
      - /var/log:/var/log
      - /app/promtail_config.yml:/etc/promtail/config.yml