route:

  group_by: ['...']

  group_wait: 1s

  group_interval: 5m

  repeat_interval: 1m

  receiver: whatsapp

  routes:
  - receiver: whatsapp
    continue: true  

receivers:
  - name: 'whatsapp'
    webhook_configs:
      - url: http://app:5000/
        http_config: {}
